spring:
  datasource:
    url: jdbc:mysql://${ute-clubs.dbAddress:localhost}:${ute-clubs.dbPort:3306}/${ute-clubs.dbDatabase:club_management}?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${ute-clubs.dbUsername}
    password: ${ute-clubs.dbPassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: ${ute-clubs.clientTimeZone:Asia/Ho_Chi_Minh}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: optional:secrets.yaml
springdoc:
  swagger-ui:
    path: /v1/swagger-ui.html
  api-docs:
    path: /v1/api-docs
server:
  error:
    include-message: always
