spring:
  datasource:
    url: jdbc:mysql://${DB_ADDRESS:localhost}:${DB_PORT:3306}/${DB_DATABASE:club_management}?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${ute-clubs.DB_USERNAME}
    password: ${ute-clubs.DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    time-zone: ${CLIENT_TIME_ZONE:Asia/Ho_Chi_Minh}
  mail:
    host: smtp.gmail.com
    username: ${ute-clubs.EMAIL_USERNAME}
    password: ${ute-clubs.EMAIL_PASSWORD}
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: optional:secrets.yaml
springdoc:
  swagger-ui:
    path: /v1/swagger-ui.html
  api-docs:
    path: /v1/api-docs
server:
  error:
    include-message: always
